language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:

notifications:
  irc: "irc.freenode.org##atoum"

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" = "7.0" ]]; then args="-ncc"; fi;

before_script:
  - composer install

script:
  - vendor/bin/atoum --test-ext $args
