language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

env:
  matrix:
    - COMPOSER_PREFER="--prefer-stable"
    - COMPOSER_PREFER="--prefer-lowest"

sudo: false

cache:
  directories:
    - vendor

matrix:
  allow_failures:
    - php: nightly
  exclude:
    - php: 7.0
      env: COMPOSER_PREFER="--prefer-stable"
    - php: nightly
      env: COMPOSER_PREFER="--prefer-stable"

notifications:
  irc: "irc.freenode.org##atoum"

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" = "7.0" ]]; then args="-ncc"; fi;

script:
  - composer update $COMPOSER_PREFER
  - vendor/bin/atoum --test-ext $args
